version: '2'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
    # environment:
    #   - BLA=ble

  # db:
  #   image: postgres
