version: '2'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_ADAPTER=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=
      - DB_HOST=db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=atm_api
